name: REGISTRY - Build Nextcloud image with extra packages

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      dev_tag:
        description: 'Latest released tag to be used in DEV (Interger only)'
        # Default value if no value is explicitly provided
        default: 33
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: number
      prod_tag:
        description: 'Production Tag (Interger only)'
        # Default value if no value is explicitly provided
        default: 32
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: number

jobs:
  dev-docker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
      # Required so the action can find the 'docker' executable/socket
      options: --user root -v /var/run/docker.sock:/var/run/docker.sock
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      -
        name: Login to REGISTRY Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          # context: .
          file: ./dev/Dockerfile
          build-args: BASE_IMAGE=nextcloud:${{ inputs.dev_tag }}-apache
          platforms: linux/amd64,linux/arm64
          push: true
        #  tags: pnatel/nextcloud-imagemagick-ffmpeg:current
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/nextcloud-imagemagick-ffmpeg:current
            ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/nextcloud-imagemagick-ffmpeg:dev
            ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/nextcloud-imagemagick-ffmpeg:nc-${{ inputs.dev_tag }}-apache
          labels: |
            org.opencontainers.image.title=nextcloud-imagemagick-ffmpeg
            org.opencontainers.image.description=Build Nextcloud Current image with imagemagick and ffmpeg packages for ARM and x86 systems     

  # prod-docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v4
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     -
  #       name: Build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         # context: .
  #         file: ./prod/Dockerfile
  #         build-args: BASE_IMAGE=nextcloud:${{ inputs.prod_tag }}-apache
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #       #  tags: pnatel/nextcloud-imagemagick-ffmpeg:current
  #         tags: |
  #           ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/nextcloud-imagemagick-ffmpeg:old
  #           ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/nextcloud-imagemagick-ffmpeg:prod
  #           ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/nextcloud-imagemagick-ffmpeg:nc-${{ inputs.prod_tag }}-apache
  #         labels: |
  #           org.opencontainers.image.title=nextcloud-imagemagick-ffmpeg
  #           org.opencontainers.image.description=Build Nextcloud Current image with imagemagick and ffmpeg packages for ARM and x86 systems   
