name: Build Nextcloud image with extra packages

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      dev_tag:
        description: 'Latest released tag to be used in DEV (Interger only)'
        # Default value if no value is explicitly provided
        default: 29
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: number
      prod_tag:
        description: 'Production Tag (Interger only)'
        # Default value if no value is explicitly provided
        default: 28
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: number

jobs:
  dev-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            pnatel/nextcloud-imagemagick-ffmpeg
          tags: |
            # type=ref,event=branch
            # type=ref,event=tag
            # type=raw,value={{branch}}-{{sha}}
            type=raw,value=current
            type=raw,value=dev
            type=raw,value=nc-${{ inputs.dev_tag }}-apache
          flavor: |
            latest=auto
          labels: |
            org.opencontainers.image.title=nextcloud-imagemagick-ffmpeg
            org.opencontainers.image.description=Build Nextcloud Current image with imagemagick and ffmpeg packages for ARM and x86 systems
          #   org.opencontainers.image.focus={{branch}}
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Tags in this release
        run: echo " ${{ steps.meta.outputs.tags }} "
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          # context: .
          file: ./docker/nextcloud-imagemagick-ffmpeg/dev/Dockerfile
          build-args: BASE_IMAGE=nextcloud:${{ inputs.dev_tag }}-apache
          platforms: linux/amd64,linux/arm64
          push: true
        #  tags: pnatel/nextcloud-imagemagick-ffmpeg:current
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}      

  prod-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            pnatel/nextcloud-imagemagick-ffmpeg
          tags: |
            type=raw,value=old
            type=raw,value=prod
            type=raw,value=nc-${{ inputs.prod_tag }}-apache
          flavor: |
            latest=auto
          labels: |
            org.opencontainers.image.title=nextcloud-imagemagick-ffmpeg
            org.opencontainers.image.description=Build Nextcloud Current image with imagemagick and ffmpeg packages for ARM and x86 systems
          #   org.opencontainers.image.focus={{branch}}
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Tags in this release
        run: echo " ${{ steps.meta.outputs.tags }} "
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          # context: .
          file: ./docker/nextcloud-imagemagick-ffmpeg/prod/Dockerfile
          build-args: BASE_IMAGE=nextcloud:${{ inputs.prod_tag }}-apache
          platforms: linux/amd64,linux/arm64
          push: true
        #  tags: pnatel/nextcloud-imagemagick-ffmpeg:current
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}    
